further quick python3 compatibility fix
Hunks

--- a/client/client.py
+++ b/client/client.py
@@ -138,10 +138,10 @@ class Mahjong:

and

--- a/client/states.py
+++ b/client/states.py
@@ -555,8 +555,8 @@ class ScoreState(RoundPreparingState):

are used to temporary fix fail-error or similar that takes place
under certain conditions on showing score screen:

File "... /rmahjong/client/states.py", line 558, in get_results
    score = (int(self.message[wind + "_score"]))
ValueError: invalid literal for int() with base 10: '27100.0'